### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by AhmadullahSaikat** [pranavpandey/dynamic-theme#1]

**Comment by pranavpandey** [comment]
You should implement the [AppTheme](https://github.com/pranavpandey/dynamic-theme/blob/master/dynamic-theme/src/main/java/com/pranavpandey/android/dynamic/theme/AppTheme.java) or [AppWidgetTheme](https://github.com/pranavpandey/dynamic-theme/blob/master/dynamic-theme/src/main/java/com/pranavpandey/android/dynamic/theme/AppWidgetTheme.java) to create a dynamic theme. 
A possible implementation (for Android) can be found [here](https://github.com/pranavpandey/dynamic-support/blob/master/dynamic-support/src/main/java/com/pranavpandey/android/dynamic/support/model/DynamicAppTheme.java).

Please check the [README](https://github.com/pranavpandey/dynamic-theme/blob/master/README.md) for more info.

**Comment by pranavpandey** [comment]
Closing it for now, please feel free to reopen.
